spring:
  ## 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  ## freemarker配置
  freemarker:
    cache: false #是否允许缓存
    charset: UTF-8 #模板编码
    content-type: text/html #Content-Type value
    expose-request-attributes: true #设置在与模板合并之前是否应该向模型添加所有请求属性
    expose-session-attributes: true #设置在与模板合并之前是否应该将所有HttpSession属性添加到模型中
    check-template-location: true #Check that the templates location exists
    prefer-file-system-access: true #对于模板加载，更喜欢文件系统访问;文件系统访问允许热检测模板更改
    suffix: .ftl #模板文件后缀
    request-context-attribute: request #所有视图的RequestContext属性的名称

  ## 文件上传设置
  servlet:
    multipart:
      max-file-size: 102400KB
      max-request-size: 102400KB
      #location: \upload_tmp #post缓存数据缓存目录
      #location: /data/upload_tmp #post缓存数据缓存目录

  jackson:
    time-zone: GMT+8 #东八区


mybatis:
  ## mybatis扫描xml路径
  mapper-locations: classpath:blog/mybatis/**/*.xml


## 异常配置
exception:
  global_default_exception_handler_page: /common/exception/webRequestExceptionHandlerPage #异常处理页面


## 安全配置
security:
  admin_login_page_url: /admin/guest/login/index #后台登录页面地址
  unauthorized_url: /common/index #未授权提示界面地址
  cache_manager_config_file: classpath:config/ehcache-shiro.xml #缓存管理器配置文件
  hash_algorithm_name: md5 #加密方式
  hash_iterations: 10 #加密散列次数
  salt_suffix: salt #盐加的后缀
  #游客可访问的路径
  anon_url_path: /css/**,/img/**,/js/**,/plugin/**,/favicon.ico,/config/ueditor/ueditorConfig/json,/admin/guest/**,/,/g.*/**,/login*/**,/logOut


## 七牛云配置
qiniu:
  # 密钥
  access_key: -------------------------------------
  secret_key: -------------------------------------
  bucket: test #空间
  cdn_prefix: http://qiniu.chenchuan.work/ #外链访问路径
  up_expire_seconds: 3600 #上传token过期时间（暂时未使用）


## 前端页面信息配置
page:
  home:
    article_rows: 10 #文章分页列表每页显示数量


server:
  tomcat:
    basedir: ${user.home}/tomcat/tmp #设置tomcat的basedir


## 第三方登录配置信息
oauth:
  qq:
    app_id: ----------------
    app_key: --------------------------------
    # 获取ocde地址
    get_authorization_code_uri: https://graph.qq.com/oauth2.0/authorize
    # 获取ocde的参数，固定为code
    response_type: code
    # 回调地址
    redirect_uri: ---------------------------
    # 获取Access Token地址
    get_access_token_uri: https://graph.qq.com/oauth2.0/token
    # 获取Access Token，固定为authorization_code
    token_grant_type: authorization_code
    # 刷新Access Token，refresh_token
    refresh_token_grant_type: refresh_token
    # 获取openid的地址
    get_openid_uri: https://graph.qq.com/oauth2.0/me
    # 获取用户信息地址
    get_user_info_uri: https://graph.qq.com/user/get_user_info